"""create songs song artists song genres and song features

Revision ID: 1f4e7a85a1ad
Revises: f04b2b154669
Create Date: 2026-07-16 21:30:31.009096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4e7a85a1ad'
down_revision: Union[str, Sequence[str], None] = 'f04b2b154669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('cover_image_path', sa.String(length=500), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='song_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_language'), 'songs', ['language'], unique=False)
    op.create_index(op.f('ix_songs_mood'), 'songs', ['mood'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_table('song_artists',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.create_table('song_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=False),
    sa.Column('instrumentalness', sa.Float(), nullable=False),
    sa.Column('liveness', sa.Float(), nullable=False),
    sa.Column('speechiness', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('loudness', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_features_id'), 'song_features', ['id'], unique=False)
    op.create_index(op.f('ix_song_features_song_id'), 'song_features', ['song_id'], unique=True)
    op.create_table('song_genres',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_genres')
    op.drop_index(op.f('ix_song_features_song_id'), table_name='song_features')
    op.drop_index(op.f('ix_song_features_id'), table_name='song_features')
    op.drop_table('song_features')
    op.drop_table('song_artists')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_mood'), table_name='songs')
    op.drop_index(op.f('ix_songs_language'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
